/**
 * Seletores estáveis do checkout para autocomplete (CodeMirror) e documentação.
 * @type {import('@codemirror/autocomplete').Completion[]}
 */
export const checkoutDomCompletions = [
    { label: '#getfy-checkout-root', type: 'constant', info: 'Página inteira (fundo)' },
    { label: '[data-checkout="page"]', type: 'constant', info: 'Equivale ao root' },
    { label: '[data-checkout="layout-inner"]', type: 'constant', info: 'Container central (max-width)' },
    { label: '[data-checkout="layout-columns"]', type: 'constant', info: 'Grid 2 colunas (principal + sidebar)' },
    { label: '[data-checkout="column-primary"]', type: 'constant', info: 'Coluna esquerda (card branco)' },
    { label: '[data-checkout="card-main"]', type: 'constant', info: 'Card resumo + formulário' },
    { label: '[data-checkout="divider-summary-form"]', type: 'constant', info: 'HR entre resumo e formulário' },
    { label: '[data-checkout="timer"]', type: 'constant', info: 'Barra de contagem regressiva' },
    { label: '[data-checkout="banners-top"]', type: 'constant', info: 'Banners acima do conteúdo' },
    { label: '[data-checkout="banners-side"]', type: 'constant', info: 'Banners na sidebar (desktop)' },
    { label: '[data-checkout="banners-side-mobile"]', type: 'constant', info: 'Banners finais (mobile)' },
    { label: '[data-checkout="youtube"]', type: 'constant', info: 'Bloco do vídeo' },
    { label: '[data-checkout="flash-error"]', type: 'constant', info: 'Alerta de erro' },
    { label: '[data-checkout="flash-success"]', type: 'constant', info: 'Mensagem de sucesso' },
    { label: '[data-checkout="flash-info"]', type: 'constant', info: 'Mensagem informativa' },
    { label: '[data-checkout="summary"]', type: 'constant', info: 'Bloco resumo do produto' },
    { label: '[data-checkout="summary-product-image"]', type: 'constant', info: 'Foto do produto' },
    { label: '[data-checkout="summary-title"]', type: 'constant', info: 'Nome do produto' },
    { label: '[data-checkout="summary-locale-currency"]', type: 'constant', info: 'Idioma e moeda' },
    { label: '[data-checkout="summary-price-row"]', type: 'constant', info: 'Preço e preço riscado' },
    { label: '[data-checkout="summary-coupon-discount"]', type: 'constant', info: 'Linha desconto cupom' },
    { label: '[data-checkout="summary-discount-badge"]', type: 'constant', info: 'Badge de desconto' },
    { label: '[data-checkout="summary-description"]', type: 'constant', info: 'Descrição do produto' },
    { label: '[data-checkout="form"]', type: 'constant', info: 'Área do formulário (seção inteira)' },
    { label: '[data-checkout="form-section-dados-header"]', type: 'constant', info: 'Título “Seus dados”' },
    { label: '[data-checkout="checkout-form-element"]', type: 'constant', info: 'Elemento <form>' },
    { label: '[data-checkout="form-errors"]', type: 'constant', info: 'Banner de erros de validação' },
    { label: '[data-checkout="form-fields"]', type: 'constant', info: 'Grid nome/email/telefone/cpf' },
    { label: '[data-checkout="field-name"]', type: 'constant', info: 'Campo nome' },
    { label: '[data-checkout="field-email"]', type: 'constant', info: 'Campo e-mail' },
    { label: '[data-checkout="field-phone"]', type: 'constant', info: 'Campo telefone' },
    { label: '[data-checkout="field-cpf"]', type: 'constant', info: 'Campo CPF' },
    { label: '[data-checkout="form-data-summary"]', type: 'constant', info: 'Resumo colapsado dos dados' },
    { label: '[data-checkout="field-coupon"]', type: 'constant', info: 'Cupom' },
    { label: '[data-checkout="order-bumps"]', type: 'constant', info: 'Order bumps (seção)' },
    { label: '[data-checkout="order-bump-card"]', type: 'constant', info: 'Card de um bump (+ data-order-bump-id)' },
    { label: '[data-checkout="payment-methods"]', type: 'constant', info: 'Formas de pagamento' },
    { label: '[data-payment-method="pix"]', type: 'constant', info: 'Botão PIX' },
    { label: '[data-payment-method="card"]', type: 'constant', info: 'Botão cartão' },
    { label: '[data-payment-method="boleto"]', type: 'constant', info: 'Botão boleto' },
    { label: '[data-checkout="form-card-panel"]', type: 'constant', info: 'Painel dados do cartão' },
    { label: '[data-checkout="form-installments"]', type: 'constant', info: 'Select de parcelas' },
    { label: '[data-checkout="form-billing-address"]', type: 'constant', info: 'Endereço (boleto/cobrança)' },
    { label: '[data-checkout="form-submit"]', type: 'constant', info: 'Botão principal (pagar/gerar)' },
    { label: '[data-checkout="form-footer-desktop"]', type: 'constant', info: 'Rodapé do formulário (desktop)' },
    { label: '[data-checkout="sidebar"]', type: 'constant', info: 'Coluna lateral' },
    { label: '[data-checkout="sidebar-summary-card"]', type: 'constant', info: 'Card resumo lateral' },
    { label: '[data-checkout="sidebar-total"]', type: 'constant', info: 'Total na sidebar' },
    { label: '[data-checkout="sidebar-trust-badge"]', type: 'constant', info: 'Selo compra segura' },
    { label: '[data-checkout="reviews"]', type: 'constant', info: 'Depoimentos' },
    { label: '[data-checkout="support-button"]', type: 'constant', info: 'Botão flutuante suporte' },
    { label: '[data-checkout="sales-notification"]', type: 'constant', info: 'Notificação de vendas' },
    { label: '[data-checkout="exit-popup"]', type: 'constant', info: 'Popup de saída' },
    { label: '[data-checkout="conversion-pixels"]', type: 'constant', info: 'Container de pixels (oculto)' },
    { label: '[data-checkout="custom-html-body-start"]', type: 'constant', info: 'HTML custom início' },
    { label: '[data-checkout="custom-html-body-end"]', type: 'constant', info: 'HTML custom fim' },
    { label: '.getfy-checkout-custom-body-start', type: 'constant', info: 'Wrapper HTML início (classe)' },
    { label: '.getfy-checkout-custom-body-end', type: 'constant', info: 'Wrapper HTML fim (classe)' },
];
